[IS-23-24]
Sputnikomk2/ProyectoSputniko pull request #27
Opened 2024-02-21 18:09 UTC by Patacabra

Listo para revisión.

2024-02-21 18:16 UTC, Carmenalbl commented
Listo para revisión https://github.com/Sputnikomk2/ProyectoSputniko/issues/26 @Juan Julián Merelo Guervó

2024-02-21 18:17 UTC, Patacabra commented
Listo para revisión @JJ

https://github.com/Sputnikomk2/ProyectoSputniko/issues/26

2024-02-21 18:40 UTC, JJ commented
OK, todavía no está listo, pero lo estará, espero, cuando fusionéis todos los issues.

2024-02-22 17:22 UTC, JJ commented
Por favor
1. Incluir en el título y cuerpo de este PR de qué se trata; este es el que eventualmente se fusionará.
2. La creación de issues no es un fin en sí, ni es una lista de tareas: es una actividad que está encaminada a dividir el problema indicado en la HU en la que estéis trabajando en trozos más pequeños, *hasta que se llegue a un trozo que se pueda programar*, en cuyo instante inmediatamente se comienza con la programación. Por favor, sed conscientes de lo que os pide vuestro próximo milestone (un modelo del problema) y con qué historia(s) de usuario estáis trabajando.

2024-02-23 09:05 UTC, JJ requested changes
Aparte de lo dicho en el comentario, ¿habéis mirado si las mejores prácticas en Python incluyen los ficheros en el directorio raíz? ¿O si el nombre del fichero tiene que seguir algún tipo de convención?
Por favor, abrid ramas de esta rama principal e id creando PRs para trabajar con los issues que se os hayan asignado.

2024-02-23 09:05 UTC, JJ commented on game1class.py
> +import random
*Siempre* debéis trabajar con PRs que revise alguien (o varios) del resto del equipo.

2024-02-23 09:06 UTC, JJ commented
Mirad también a ver si os hace falta el fichero de Jupyter notebooks.

2024-02-26 15:59 UTC, JJ commented
Por favor, añadidle un título más allá de los corchetes. Un PR tiene que tener un título explicativo.

2024-02-26 17:25 UTC, closed without merging

2024-02-27 18:08 UTC, JJ commented
¿Por qué habéis cerrado esto? Este es el PR con la rama a la que tiene que ir todo.