[IS-2324] #41 Ideas para un mejor aprendizaje
Sputnikomk2/ProyectoSputniko pull request #44
Opened 2024-02-26 18:55 UTC by JoseASR

close #41
En el archivo doc/#41.md adjunto algunas de las ideas para que el juego sea mas fácil, intuitivo y llamativo.
En el archivo puntuacion.py explico la forma de puntuación del juego, así como los premios correspondientes, para incentivar aun mas a los usuarios.
https://github.com/Sputnikomk2/ProyectoSputniko/blob/joselevel2/doc/%2341.md
https://github.com/Sputnikomk2/ProyectoSputniko/blob/joselevel2/game/puntuacion.py

2024-02-26 19:03 UTC, Patacabra commented
Buenas ideas! Es muy importante mantener un fácil aprendizaje para fomentar su uso.

2024-02-26 19:32 UTC, Carmenalbl commented on doc/#41.md
¿Crees que añadir música también seria buena idea?

2024-02-26 19:33 UTC, JoseASR commented on doc/#41.md
Buenísima idea, la adjunto! ;)

2024-02-27 18:06 UTC, JJ commented
Tratad de poner un título descriptivo al PR. Todos van a ser solución de un issue.

2024-03-05 15:49 UTC, JoseASR commented
Buenas tardes, cuando pueda revisión @JJ

2024-03-05 15:58 UTC, JJ commented
Ninguno de los mensajes de commit menciona el issue con el que estás trabajando, por lo que es imposible saber qué es lo que está haciendo y por qué.
Por otro lado, el cuerpo del PR debe enlazar el issue con el que trabaja (eso está bien) y también explicar qué es lo que hace, no enlazar ficheros en internet. Por favor, corrígelo.
En cuanto al código, si los mensajes de commit no enlazan ningún issue, el código resultante no se puede evaluar. Por favor, reescríbelo teniendo siempre en mente qué estás haciendo y explicando en el mensaje de commit de qué forma resuelve el problema.

2024-03-05 16:05 UTC, JJ requested changes
Conviene también que echéis un vistazo todos a este PR; quizás @carlosalvarez puede también aportar algo.

2024-03-05 17:00 UTC, JoseASR commented
@JJ he modificado según sus indicaciones, para su revisión.
Gracias

2024-03-05 17:04 UTC, JJ commented
En este PR no se ha añadido ningún código siguiendo las buenas prácticas en los mensajes de commit. Ahora mismo, además, está posiblemente dessincronizado con la rama principal; tiene ficheros que se han borrado de ahí o se han modificado. Habría que hacer alguna cosa
1. Sincronizar con `level2`
2. Borrar lo que todavía quede y que no esté en `level2`
3. Crear desde 0 código que pueda resolver el problema que hay en el issue #44, si es que realmente se puede.

2024-03-05 18:27 UTC, closed without merging