[IS-2324] #40 OBJETIVOS
Sputnikomk2/ProyectoSputniko pull request #45
Opened 2024-02-26 19:28 UTC by Carmenalbl

CLOSES #40 

- Voy a trabajar con los objetivos principales en los que nos basaremos

2024-02-26 19:31 UTC, Patacabra commented
👍

2024-02-26 19:40 UTC, JJ requested changes
Creo que has avanzado en la comprensión del problema, y eso está bien; pero el modelo que te pide el milestone 0 tiene que ser en forma de código.

2024-02-26 19:40 UTC, JJ commented on doc/objetivos.md
> +Tenemos dos objetivos principales.
Todo el texto es mejor que lo pongas en el issue correspondiente, añadiendo información donde sea pertinente.

2024-02-26 19:40 UTC, JJ commented on is.yaml
> +lenguaje: python
Esto no sé qué hace aquí ahora. ¿No debería estar en la rama principal?

2024-02-27 17:03 UTC, JJ requested changes
Enhorabuena por tu primer código en Python, convendría de todas formas que le dieras una vueltecilla.

2024-02-27 17:03 UTC, JJ commented on doc/Aprendizaje.py
> +class Aprendizaje:
¿Crees que esto corresponde al #40, que habla de los *objetivos* que hay que cumplir?

2024-02-27 17:03 UTC, JJ commented on doc/Aprendizaje.py
> +    def obtener_aprendizaje_nivel1(self):
Para empezar, no hace falta usar getters. Pero para seguir, si se usan getters se les declara de una forma determinada en Python, que no es esta.

2024-02-27 17:03 UTC, JJ commented on doc/Aprendizaje.py
> +    def __init__(self,nivel2):
Si lo que quieres es inicializar dos variables de instancia, debes llamar a una sola función con dos argumentos (3, incluyendo `self`)

2024-02-27 17:56 UTC, JJ commented
¿Crees que eso estaría mejor como parte del cuerpo del PR? ¿Puedes editarlo e incluirlo ahí?
Si esos son los objetivos, ¿cómo sería el modelo de datos que lo codificaría?

2024-02-27 19:12 UTC, JJ commented
Me temo que ahora mismo solo hay un fichero .ipynb y está vacío.

2024-02-27 19:30 UTC, Carmenalbl commented
@JJ Listo para revisión

2024-03-04 14:56 UTC, JJ commented
Los mensajes de commit siempre tienen que hacer referencia a algún issue.

2024-03-04 14:57 UTC, JJ reviewed
Veo tres ficheros, ¿los tres tienen relación con el problema?
Por otro lado, ¿no sería mejor poner las dos constantes en una sola, para poder usarla como referencia?

2024-03-04 18:00 UTC, closed without merging