[IS-23-24] closed #40 he trabajado el objetivo principal del juego
Sputnikomk2/ProyectoSputniko pull request #53
Opened 2024-03-04 18:07 UTC by Carmenalbl

2024-03-04 18:13 UTC, Carmenalbl commented
@JJ  Necesita revisión.

2024-03-04 18:25 UTC, JJ requested changes
También, ¿no sería conveniente que todos los objetivos estuvieran en una sola variable y se pudiera elegir?

2024-03-04 18:25 UTC, JJ commented on doc/objetivos.py
> +motivation_factor = "Aprender divitiéndose con el medio ambiente"
¿No había más objetivos?

2024-03-04 18:27 UTC, JJ commented
Tienes que poner "close", no "closes", y en el cuerpo del PR. De esa forma, GitHub lo enlazará automáticamente.

2024-03-04 18:36 UTC, JJ commented
Gracias por incluir un mensaje de commit con menos de 50 caracteres para que GitHub no lo parta, pero ¿crees que aporta alguna información a lo que has hecho? También, ¿crees que sigue las mejores prácticas de referirse *siempre* a un issue?

2024-03-04 18:37 UTC, JJ commented
¿Crees también que el directorio `doc` es el adecuado para este fichero?

2024-03-04 18:38 UTC, JJ commented
Eso no es el cuerpo del PR, sino un comentario.
Por favor, mira también [los enums en Python](https://docs.python.org/3/library/enum.html) para ver si pudieran ser una mejor solución a tu problema.

2024-03-04 19:18 UTC, JJ approved these changes
👍 ¿Le podéis echar un vistazo el resto?

2024-03-04 19:26 UTC, Patacabra commented
👍

2024-03-04 19:29 UTC, Patacabra commented
@JoseASR @JoseASR 

Revisadlo también! 👯

2024-03-05 15:22 UTC, JoseASR approved these changes

2024-03-05 15:23 UTC, Franjapeji approved these changes

2024-03-05 15:25 UTC, merged

2024-03-05 15:35 UTC, Franjapeji commented on juegoSputniko/objetivos.py
Buenas tardes Carmen, no sé exactamente qué hace tu código de definir tu constante. Me falta contexto. Un saludo.

2024-03-05 15:41 UTC, JJ commented on juegoSputniko/objetivos.py
Ahora es difícil comentar aquí, ¿igual podías repetirlo cuando se cree el PR de `level2` a `main` que incorpore ese código?

2024-03-05 15:44 UTC, JoseASR commented on juegoSputniko/objetivos.py
Has definido una enumeración de los objetivos en dos elementos.....
aprendizaje y motivación..
Yo lo veo bien!!!!!!

2024-03-05 15:55 UTC, JJ commented on juegoSputniko/objetivos.py
@JoseASR ¿y entiendes cómo resuelve eso el issue del que se trata?